Implement mypy import workaround

diff --git a/scripts/typecheck b/scripts/typecheck
--- a/scripts/typecheck
+++ b/scripts/typecheck
@@ -43,15 +43,28 @@ function check {
 
 
     echo ""
-    echo "Checking ./test..."
+    echo "Checking ./test/unit..."
     echo ""
-    mypy test
+    mypy test/unit
     mypy_tests_result=$?
 
     if [ $mypy_tests_result != 0 ]; then
         echo "Error in typechecking, see output above."
         exit $mypy_tests_result
     fi
+
+
+    echo ""
+    echo "Checking ./test/integration..."
+    echo ""
+    mypy test/integration
+    mypy_tests_result=$?
+
+    if [ $mypy_tests_result != 0 ]; then
+        echo "Error in typechecking, see output above."
+        exit $mypy_tests_result
+    fi
+
 
     # return to scripts directory
     cd $SCRIPT_DIR
